
test:cargo:
  image: rust:latest
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --all --verbose

build:docker:
  image: ${CI_REGISTRY}/shared-ci-docker-images/docker:latest
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    #  Service image
    - docker build --network=host -t nightingale:${CI_COMMIT_SHA} .
    - docker tag nightingale:${CI_COMMIT_SHA} ${DOCKER_REGISTRY}/nightingale:${CI_COMMIT_SHA}
    - docker tag nightingale:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    # Push to ECR for deployment
#    - docker push ${DOCKER_REGISTRY}/nightingale:${CI_COMMIT_SHA}
    # Push to gitlab for e2e testing
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
