[package]
name = "nightingale"
version = "0.1.0"
authors = ["Zak Henry <zak@cloudnc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
